services:
  - type: web
    name: project-one
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project_one.wsgi:application --bind 0.0.0.0:$PORT
